name: PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Build api Docker image
        uses: docker/build-push-action@v5
